name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # deploy when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install huggingface_hub

      - name: Deploy files to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<EOF
          from huggingface_hub import Repository
          import os, shutil

          # HF Space repo URL
          REPO_URL = "https://huggingface.co/spaces/Shahida13/text-summarizer"
          LOCAL_DIR = "hf_space_temp"

          # Clone HF Space repo
          repo = Repository(local_dir=LOCAL_DIR, clone_from=REPO_URL, use_auth_token=os.environ["HF_TOKEN"])

          # Copy all files from current repo to Space folder
          for item in os.listdir("."):
              if item == ".git" or item.startswith(".github"):
                  continue
              src = os.path.join(".", item)
              dst = os.path.join(LOCAL_DIR, item)
              if os.path.isdir(src):
                  shutil.copytree(src, dst, dirs_exist_ok=True)
              else:
                  shutil.copy2(src, dst)

          # Commit and push
          repo.git_add(auto_lfs_track=True)
          repo.git_commit("Update from GitHub Actions")
          repo.git_push()
          EOF
