name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Hugging Face Hub client
        run: pip install huggingface_hub

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -m huggingface_hub.commands.upload \
            --repo-type space \
            --repo-id Shahida13/text-summarizer \
            --token $HF_TOKEN \
            --dir .
