name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt huggingface_hub

      - name: Deploy to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<EOF
          import os, shutil
          from huggingface_hub import Repository

          REPO_URL = "https://huggingface.co/spaces/Shahida13/text-summarizer"
          LOCAL_DIR = "hf_space_temp"

          # Remove previous folder if exists
          if os.path.exists(LOCAL_DIR):
              shutil.rmtree(LOCAL_DIR, ignore_errors=True)

          # Clone HF Space
          repo = Repository(local_dir=LOCAL_DIR, clone_from=REPO_URL, use_auth_token=os.environ["HF_TOKEN"])

          # Remove all old files except README.md and .gitattributes
          for f in os.listdir(LOCAL_DIR):
              if f not in ["README.md", ".gitattributes"]:
                  path = os.path.join(LOCAL_DIR, f)
                  if os.path.isdir(path):
                      shutil.rmtree(path)
                  else:
                      os.remove(path)

          # Copy all files from GitHub repo to HF Space folder
          for item in os.listdir("."):
              if item == ".git" or item.startswith(".github"):
                  continue
              src = os.path.join(".", item)
              dst = os.path.join(LOCAL_DIR, item)
              if os.path.isdir(src):
                  shutil.copytree(src, dst, dirs_exist_ok=True)
              else:
                  shutil.copy2(src, dst)

          # Commit & push changes
          repo.git_add(auto_lfs_track=True)
          try:
              repo.git_commit("Deploy from GitHub Actions")
          except:
              print("Nothing to commit")
          repo.git_push()
          EOF
